export const majorViolation = [
  'Smoking or vaping',
  'Possession of alcoholic beverages or coming to school under the influence of alcohol',
  'Tampering of posters or other school information media',
  'Refusal to submit to reasonable inspection conducted by authorized personnel',
  'Bringing outsiders or providing any means for entry in the University premises without consent of the concerned authority',
  'Ridiculing of fellow students / Rumor mongering',
  'Failure to appear before school authorities when required to report within 48 hours without valid reason',
  'Lewd Act / Boisterous remark / Use of profane or indecent language (e.g., catcalling, etc.)',
  'Public Display of Affection such as, but not limited to embracing, petting, kissing, suggestive, vulgar, or indecent poses',
  "Unauthorized use of PLV logo or seal, or other university markers or symbols including accredited students' organizations",
  'Unauthorized representation to any activity / event / opportunity in behalf of the University, student organization, student, council officer, school authorities, or officials',
  'Willful affiliation with any unrecognized organization within PLV',
  'Physical, verbal, or written assault on student, organization, or school authorities',
  "Lending or borrowing one's ID, COR, or Library Card for the use of another person / Other forms of misrepresentation",
  'Use of class / organizational funds for personal benefit',
  'Unauthorized solicitation or collection of money from students and other school authorities',
  'Vandalism / Defacing walls / Tearing pages from library materials or school documents / Unauthorized removal of official notices and posters',
  'Destruction of school properties / equipment',
  'Any form of coercion or threat against any student, faculty member, University guest, or any school authority',
  'Disrespect towards school personnel, faculty members, or school authorities',
  'Possession of pornographic material/s in any form',
  'Unauthorized possession and/or use of playing cards or devices inside the school premises / Indulging in any form of betting or gathering',
  'Any form of cheating during examinations or in any academic work',
  "Plagiarism or submission of another person's work and claiming it as his/her own",
  'Any form of bullying, harassment, threat, or intimidation against students, school personnel, faculty members, and school authorities',
  'Membership in gangs, fraternities, sororities, or recruitment of students to the same',
  'Any form hazing or infliction of physical or mental harm or ordeal to student as a requirement for entry to student organizations in the university',
  'Illegal possession, use, sale, or disposal of prohibited drugs',
  'Arson',
  'Grave sexual misconduct constituting a criminal offense (such as, but not limited to, acts of lasciviousness)',
  'Rebellious actions such as, but not limited to, pressuring others to boycott classes, or leading or participating in unauthorized activities',
  'Organizing (what type of group) groups and/or inviting membership to unrecognized/accredited organizations or groups by PLV',
  'Any form of falsification, tampering, or submission of fraudulent school records or credentials, such as, but not limited to, I.D., Receipt, and other documents / materials',
  'Carrying deadly weapons of any kind (firearms, knives, and the likes) or possession of explosives',
  'Inflicting physical injury / assault on students, school personnel, faculty members, or school authorities without provocation on the part of the latter',
  'Any form of stealing, swindling, or extortion rebellious',
  'Disclosing or misusing confidential or classified school information',
  'Posting of statements through any system of communication, channel, or publications, which damage the reputation of the university or its community',
  'Bring dishonor to the University',
];

export const minorViolation = [
  'Incomplete uniform',
  'Sporting very sophisticated hair style, clothing, and accessories',
  'Unkempt / Long hair for boys',
  'Hair dyeing',
  'Sporting visible tattoos',
  'Excessive body piercing',
  'Littering',
  'Loitering',
  'Unauthorized use of classrooms and other school facilities and supplements',
  'Unauthorized entry to restricted and designated areas',
];

export const caseStatuses = [
  'Pending',
  'Investigation',
  'Evaluation',
  'Undertaking',
  'Dismissed',
  'Categorization',
  'Show Cause',
  'Referral',
  'Hearing',
  'Decision',
  'Appeal',
  'Implementation',
  'Case Solved',
];

export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const chartColors = [
  '#006bff',
  '#FFBF00',
  '#FF5F1F',
  '#ff3131',
  '#10b981',
  '#8b5cf6',
  '#ec4899',
  '#14b8a6',
  '#f97316',
  '#6366f1',
];

export const chartColorsBg = [
  'rgba(0, 107, 255, 0.15)',
  'rgba(255, 191, 0, 0.15)',
  'rgba(255, 95, 31, 0.15)',
  'rgba(255, 49, 49, 0.15)',
  'rgba(16, 185, 129, 0.15)',
  'rgba(139, 92, 246, 0.15)',
  'rgba(236, 72, 153, 0.15)',
  'rgba(20, 184, 166, 0.15)',
  'rgba(249, 115, 22, 0.15)',
  'rgba(99, 102, 241, 0.15)',
];
